### ISSUE TITLE
Error when connecting to the ArgoCD backend

### ISSUE THREAD

**Issue by lnetrebskii** [VirtoCommerce/vc-deploy-apps#2]
**Steps to reproduce:**
1. Setup argocd according to [https://argoproj.github.io/argo-cd/cli_installation/](instructions)
1. Create a JWT token from [https://cd.govirto.com/settings/projects/tenant?tab=roles&editRole=admin](here)
1. Run command
`argocd app wait platform-app --auth-token ARGO_TOKEN --server cd.govirto.com`

**Actual result:**
Error
`FATA[0002] rpc error: code = Unavailable desc = transport is closing`

**Expected result:**
CLI waits until synchronization is finished

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2720 has been created

**Comment by Woland2k** [comment]
You can use the following command to login with argocd: 
```
argocd login cd.govirto.com --sso --grpc-web
```
